# Generated by Django 3.2.8 on 2021-11-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_likedposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedposts',
            name='posts',
        ),
        migrations.AddField(
            model_name='likedposts',
            name='posts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='network.post'),
        ),
    ]
