# Generated by Django 3.2.8 on 2021-11-28 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20211128_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedposts',
            name='post',
        ),
        migrations.AddField(
            model_name='likedposts',
            name='posts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='network.post'),
        ),
        migrations.AlterField(
            model_name='likedposts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Likedposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
