# Generated by Django 3.2.8 on 2021-11-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20211128_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedposts',
            name='posts',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='network.post'),
        ),
    ]
