# Generated by Django 3.2.8 on 2021-11-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_alter_likedposts_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedposts',
            name='posts',
        ),
        migrations.AddField(
            model_name='likedposts',
            name='post',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='likedposts',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
